In [1]:
print("hello world")


hello world


In [1]:
class movies:
    def __init__(self,names,producers,budget,screenplay):
        self.names=names
        self.producers=producers
        self.budget=budget
        self.screenplay=screenplay
        
        
    def list(self):
        print(self.names,self.producers,self.budget,self.screenplay)
        
        
        
m1=movies("The Batman","WB","100 million","Nolan")

m1.list()

The Batman WB 100 million Nolan


In [18]:
class laptop:
    def __init__(self,name,brand,cost,ram,hdd,ssd,speed,cam,speakers,blit):
        self.name=name
        self.brand=brand
        self.cost=cost
        self.ram=ram
        self.hdd=hdd
        self.ssd=ssd
        self.speed=speed
        self.cam=cam
        self.speakers=speakers
        self.blit=blit
        
        
    def specs2(self):
        print(self.ram,
              self.hdd,
              self.ssd,
              self.speed,
              self.cam,
              self.speakers,
              self.blit,
              self.name,
              self.brand,
              self.cost)
        
       
        
l1=laptop( "macbook","apple","1200 $","16gb","1 tb","512 gb","3 ghz","1080p","B&O","yes")

l1.specs2()

print(l1.brand)

print(l1.speed)



16gb 1 tb 512 gb 3 ghz 1080p B&O yes macbook apple 1200 $
apple
3 ghz


In [9]:
from numpy import *


m1=matrix('1 2 3  ;  7 8 9 ; 4 5 6 ')
m2=matrix('1 2 4  ;  6 8 9 ; 4 5 7 ')

m3=m1+m2
print(m3.reshape(3,3))
print(m3)


        


[[ 2  4  7]
 [13 16 18]
 [ 8 10 13]]
[[ 2  4  7]
 [13 16 18]
 [ 8 10 13]]


In [12]:
result=eval(input("enter the values for calculation"))
print(result)


enter the values for calculation3+3
6
